services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/xdebug.ini:/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - '8000:80'
  db:
    image: mariadb
    volumes:
      - maria-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ecomdb
      MARIADB_ROOT_PASSWORD: ecomdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3308:3306'
volumes:
  maria-data:
